repos:
  # Автоформатирование Black
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
#
#  # Сортировка импортов
#  - repo: https://github.com/PyCQA/isort
#    rev: 5.12.0
#    hooks:
#      - id: isort
#
#  # Линтер Flake8
#  - repo: https://github.com/PyCQA/flake8
#    rev: 7.0.0
#    hooks:
#      - id: flake8
#
#  # Проверка на наличие TODO/FIXME в коде
#  - repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v4.6.0
#    hooks:
#      - id: check-todo
