services:

  tests_ui:
    build:
      context: tests/ui/python_playwright/sync
      dockerfile: Dockerfile_test_ui
    #    command: tail -f /dev/null
    environment:
      - HEADLESS=True
      - SLOW_MO=0
    volumes:
      - allure-results:/test_ui/allure-results

  allure:
    #   GUI report will be here >>> http://localhost:5050/allure-docker-service/latest-report

    image: frankescobar/allure-docker-service
    container_name: allure-server
    ports:
      - "5050:5050"
    volumes:
      - allure-results:/app/allure-results
    depends_on:
      - tests_ui

volumes:
  allure-results: