services:
  #  db:

  api:
    build:
      context: app
      dockerfile: Dockerfile_app
    ports:
      - "8000:8000"
    networks:
      - docker_net
  #    depends_on:
  #      - db

  tests_api:
    build:
      context: .
      dockerfile: Dockerfile_test_api
    environment:
      - BASE_URL=http://api:8000
    volumes:
      - allu-res:/app/allure-results
    depends_on:
      - api
    networks:
      - docker_net

  tests_ui:
    build:
      context: .
      dockerfile: Dockerfile_test_ui
    environment:
      - HEADLESS=True
      - SLOW_MO=0
    volumes:
      - allu-res:/app/allure-results
    depends_on:
      - tests_api
    networks:
      - docker_net

  allure:
    #   GUI report will be here >>> http://localhost:5050/allure-docker-service/latest-report

    image: frankescobar/allure-docker-service
    container_name: allure-server
    ports:
      - "5050:5050"
    volumes:
      - allu-res:/app/allure-results
    depends_on:
      - tests_ui
    networks:
      - docker_net

networks:
  docker_net:
    driver: bridge

volumes:
  allu-res: