services:

  api:
    build:
      context: app
      dockerfile: Dockerfile_app
    ports:
      - "8000:8000"
    volumes:
      - app_data:/app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://api:8000/" ]
      interval: 1s
      timeout: 1s
      start_period: 1s

  tests_api:
    build:
      context: tests/api
      dockerfile: Dockerfile_test_api
    environment:
      - BASE_URL=http://api:8000
    volumes:
      - allure-results:/test_api/allure-results
      - app_data:/app
    depends_on:
      api:
        condition: service_healthy

  tests_ui:
    build:
      context: tests/ui/sync
      dockerfile: Dockerfile_test_ui
    environment:
      - HEADLESS=True
      - SLOW_MO=0
    volumes:
      - allure-results:/test_ui/allure-results

  tests_ui_async:
    build:
      context: tests/ui/async
      dockerfile: Dockerfile_test_ui_async
    environment:
      - HEADLESS=True
      - SLOW_MO=0
    volumes:
      - allure-results:/test_ui/allure-results

  allure:
    # web-report will be here >>> http://localhost:5050/allure-docker-service/latest-report
    image: frankescobar/allure-docker-service:2.27.0
    container_name: allure-server
    ports:
      - "5050:5050"
    volumes:
      - allure-results:/app/allure-results

volumes:
  app_data:
  allure-results:

