services:
#  db:

  api:
    build: app
    ports:
      - 8000:8000
#    depends_on:
#      - db

  tests:
    build: tests
    depends_on:
      - api

  allure:
    image: allure/allurectl

    depends_on:
      - tests