services:
  #  db:

  api:
    build:
      context: app
      dockerfile: Dockerfile_app
    ports:
      - "8000:8000"
    volumes:
        - app_data:/app
    networks:
      - docker_net
  #    depends_on:
  #      - db

  tests_api:
    build:
      context: tests/api/test_api
      dockerfile: Dockerfile_test_api
#    command: tail -f /dev/null
    environment:
      - BASE_URL=http://api:8000
    volumes:
      - allure-results:/test_api/allure-results
      - app_data:/app
    depends_on:
      - api
    networks:
      - docker_net

  tests_ui:
    build:
      context: .not_for_git/test_ui
      dockerfile: Dockerfile_test_ui
#    command: tail -f /dev/null
    environment:
      - HEADLESS=True
      - SLOW_MO=0
    volumes:
      - allure-results:/test_ui/allure-results
    depends_on:
      - tests_api
    networks:
      - docker_net

  allure:
    #   GUI report will be here >>> http://localhost:5050/allure-docker-service/latest-report

    image: frankescobar/allure-docker-service:2.27.0
    container_name: allure-server
    ports:
      - "5050:5050"
    volumes:
      - allure-results:/app/allure-results
    depends_on:
      - tests_ui
    networks:
      - docker_net

networks:
  docker_net:
    driver: bridge

volumes:
  app_data:
  allure-results: