# Из-за моделек, которые в папке app, запускаемся на верхнем уровене.
# Поэтому нужно правильно копировать файлы и правильно запустить pytest

FROM python:3.13-alpine

WORKDIR /app

COPY tests/api/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# нельзя копировать конкретные файлы (например models.py) !!!!
# т.к. он ищет Пайтон пакеты, т.е. в папке должнен быть еще __init__.py
COPY app ./app
COPY tests ./tests
COPY pytest.ini .

CMD ["pytest", "tests/api/"]
#CMD ["pytest", "-sv", "--alluredir=allure-results"]
