# здесь копируем не только папку tests, но и папку api, тк там модельки.
# Поэтому запускаемся как бы на уровень повыше чем в остальных контейнерах
FROM python:3.13
#FROM python:3.13-slim

WORKDIR /app

COPY tests/api/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# мб попробовать копировать только один файл models, короче вот так
#COPY app/models.py ./app
#COPY tests .
#COPY pytest.ini .

# нельзя копировать конкретные файлы !!!! т.к. он смотри на Пайтон пакеты, т.е. в папке должнен быть __init__.py

COPY app ./app
COPY tests ./tests
COPY pytest.ini .

#COPY . .

CMD ["pytest", "tests/api/"]
#CMD ["pytest", "-sv", "--alluredir=allure-results"]
