version: '3.9'

services:
  tests:
    build: .
    volumes:
      - .:/app
      - ./allure-results:/app/allure-results
    environment:
      - PYTHONUNBUFFERED=1

  allure:
    image: frankescobar/allure-docker-service:latest
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
