FROM python:3.13-slim

WORKDIR /test_ui
ENV PYTHONPATH=/test_ui

RUN apt-get update && apt-get install -y \
    curl \
    wget \
    gnupg \
    unzip \
    libnss3 \
    libatk-bridge2.0-0 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libgbm1 \
    libasound2 \
    libatk1.0-0 \
    libcups2 \
    libxshmfence1 \
    libgtk-3-0 \
    libdrm2 \
    libxfixes3 \
    fonts-liberation \
    xdg-utils \
    && rm -rf /var/lib/apt/lists/*

#RUN apt update && apt install -y curl unzip && rm -rf /var/lib/apt/lists/*

# еще вот так видел, надо как-нибудб попробовать
#RUN apt-get update && apt-get install -y \
#    curl \
#    git \
#    unzip \
#    wget \
#    && apt-get clean

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

RUN playwright install chromium --with-deps

COPY .. .

CMD ["pytest"]