FROM python:3.13-alpine

WORKDIR /workdir

COPY tests/api/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY tests/api/ .
COPY app ./app

ENV PYTHONPATH=/workdir

CMD ["pytest"]
