FROM python:3.13-alpine

WORKDIR /workdir

COPY tests/api/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY tests/api2/ .
#COPY app ./app

ENV PYTHONPATH=/workdir


# Делаем entrypoint исполняемым
RUN chmod +x workdir/entrypoint.sh

ENTRYPOINT ["workdir/entrypoint.sh"]


#CMD ["pytest"]
