FROM python:3.13-alpine
ENV PYTHONUNBUFFERED=1

WORKDIR /test_api
ENV PYTHONPATH=/test_api

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["pytest"]
#CMD ["sleep", "infinity"]